name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: d58e20f5904a1b18d609e1eca6de86c8752d4c9439ebbeca025ecc9a551940d3
      ENCRYPT_KEY: 77588f4eccddd7f57f2514e64ef2873e169445adae7de09c2b872404abbbe5cb
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5433/testdb
      DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5433/testdb # Same url, gets overriden in tests
      # These are not real secret keys: For CI testing only

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
        
      - name: Run tests
        run: poetry run pytest tests/ -q
    
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Format check
        run: poetry run ruff format --check .

      - name: Lint
        run: poetry run ruff check .

      - name: Type check
        run: poetry run mypy .