name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: secret-key-test
      # This is not a real secret key: For CI testing only
      ENCRYPT_KEY: 77588f4eccddd7f57f2514e64ef2873e169445adae7de09c2b872404abbbe5cb
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install required dependencies
        run: pip install -r requirements.txt

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
        
      - name: Run tests
        run: python -m pytest tests/ -q
    
